config/routes.rb
Rails.application.routes.draw do

  resources :reviews
  resources :books

  get 'reading-list' => 'books#index'
  get 'reward-leaderboard' => 'static#reward_leaderboard_placeholder'

  devise_for :users

  get 'timeline' => 'static#timeline'
  get 'welcome' => 'static#welcome'

  root 'static#welcome'

end

app/models/book.rb
class Book < ActiveRecord::Base
  mount_uploader :picture, PictureUploader

  has_many :reviews

  validates :category, presence: true
  validates :title, presence: true, uniqueness: true

  default_scope { order(category: :desc) }
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :book
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    return "/reading-list"
  end
  def after_sign_up_path_for(resource)
    return "/reading-list"
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :value, :buy_url, :description, :category, :picture)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :require_current_user, only: [:new, :edit, :update, :destroy, :create]

  # GET /reviews
  # GET /reviews.json
  def index
    @books = Book.includes(:reviews)
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
    @review.book_id = params[:book_id]
    @review.user_id = current_user.id
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to reviews_path, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:book_id, :user_id, :title, :summary, :rating, :recommended)
    end

    def require_current_user
      return redirect_to new_user_session_path, error: "You must be signed in to review a book." unless current_user
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def timeline
  end

  def welcome
  end

  def book_reviews_placeholder
    return redirect_to root_path, notice: "Book reviews are coming soon!"
  end
  def reading_list_placeholder
    return redirect_to root_path, notice: "The reading list is coming soon!"
  end
  def reward_leaderboard_placeholder
    return redirect_to root_path, notice: "The reward leaderboard is coming soon!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when "notice" then "alert alert-info"
      when "warning" then "alert alert-warning"
      when "success" then "alert alert-success"
      when "error" then "alert alert-danger"
      when "alert" then "alert alert-danger"
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def recommendation_count(book)
    return "#{(book.reviews.where(recommended: true).count / book.reviews.count)*100.floor}%"

  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/books/_form.html.haml
= form_for @book do |f|
  - if @book.errors.any?
    #error_explanation
      %h2= "#{pluralize(@book.errors.count, "error")} prohibited this book from being saved:"
      %ul
        - @book.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :value
    = f.text_field :value
  .field
    = f.label :buy_url
    = f.text_area :buy_url
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :category
    = f.text_field :category
  .field
    = f.label :picture
    = f.hidden_field(:picture_cache)
    = f.file_field(:picture)
  .actions
    = f.submit 'Save'

app/views/books/edit.html.haml
%h1 Editing book

= render 'form'

= link_to 'Show', @book
\|
= link_to 'Back', books_path

app/views/books/index.html.haml
:javascript
  $( document ).ready(function() {
    $(".more-btn").on('click', function(){
      $(this).hide();
      $(this).siblings(".less-btn").show();
      $(this).siblings(".description").removeClass("more").addClass("less");
    });
    $(".less-btn").on('click', function(){
      $(this).hide();
      $(this).siblings(".more-btn").show();
      $(this).siblings(".less").removeClass("less").addClass("more");
    });
  });

%h1 Reading List
%h2.pad-bottom
  Reading your way to
  %em excellence

- @books.each do |book|
  .col-sm-6.col-lg-4
    .panel.book-panel{ class: "#{book.category.downcase.gsub(' ', '_')}"}
      .panel-heading
        .title= book.title
        .value
          = "$#{book.value}"
          %br
          .reward REWARD
      .picture{style: "background-image: url('#{book.picture_url(:small)}');"}
      .buttons
        .col-xs-6.button.first
          = book.buy_url.html_safe
        .col-xs-6.button
          = link_to 'Review', new_review_path(book_id: book.id)
      .description-container
        .description.more
          = book.description.gsub("\n", "<br/>").html_safe
        .more-btn MORE
        .less-btn LESS
      .panel-footer
        .category= book.category

app/views/books/new.html.haml
%h1 New book

= render 'form'

= link_to 'Back', books_path

app/views/books/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @book.title
%p
  %b Value:
  = @book.value
%p
  %b Buy url:
  = @book.buy_url
%p
  %b Description:
  = @book.description
%p
  %b Category:
  = @book.category

%p
  %b Picture:
  = image_tag @book.picture_url(:thumbnail)

= link_to 'Edit', edit_book_path(@book)
\|
= link_to 'Back', books_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Readingisforwinners
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{content: "width=device-width, initial-scale=1, maximum-scale=1", name: "viewport"}
  %body
    = render('shared/navbar')
    = render('shared/flash')
    = yield

app/views/reviews/_form.html.haml
:javascript
  $(document).ready(function() {
    $("select.disable-first option:first").attr("disabled", "disabled").val("");
  });

= form_for @review do |f|
  - if @review.errors.any?
    #error_explanation
      %h2= "#{pluralize(@review.errors.count, "error")} prohibited this review from being saved:"
      %ul
        - @review.errors.full_messages.each do |msg|
          %li= msg

  .field
    %br
    = f.hidden_field :book_id, value: @review.book_id
  .field
    %br
    = f.hidden_field :user_id, value: @review.user_id
  .field
    %br
    = f.text_field :title, placeholder: "Review Title"
  .field
    %br
    = f.text_area :summary, placeholder: "Review Copy / Book Highlights"
  .field
    %br
    = f.select :rating, ["Rating: 1-5", "1", "2", "3", "4", "5"], {}, class: "disable-first"
  .field
    %br
    .field-container
      = f.check_box :recommended
      = f.label "Would you recommend this book?"
  .field
    %br
    = f.submit 'Share Review'

app/views/reviews/edit.html.haml
%h1 Editing review

= render 'form'

= link_to 'Show', @review
\|
= link_to 'Back', reviews_path

app/views/reviews/index.html.haml
:javascript
  $( document ).ready(function() {
    $(".more-btn").on('click', function(){
      $(this).hide();
      $(this).siblings(".less-btn").show();
      $(this).siblings(".description").removeClass("more").addClass("less");
    });
    $(".less-btn").on('click', function(){
      $(this).hide();
      $(this).siblings(".more-btn").show();
      $(this).siblings(".less").removeClass("less").addClass("more");
    });
  });

%h1 Book Reviews
%h2.pad-bottom
  See what your
  %em coworkers
  are saying

- @books.each do |book|
  - if book.reviews.count > 0
    .col-sm-6.col-lg-4
      .panel.book-panel.review-panel{ class: "#{book.category.downcase.gsub(' ', '_')}"}
        .panel-heading
          .title= book.title
          .value.reviews
            = pluralize(book.reviews.count, "Review")
            .reward
              = "#{recommendation_count(book)} RECOMMENDED"
        .picture{style: "background-image: url('#{book.picture_url(:small)}');"}
        - book.reviews.each_with_index do |review, i|
          .description-container
            .review-count
              = "Review #{i+1}"
            .review-info
              %em= review.user.email
              = "- #{review.rating} stars"
            .review-title
              = review.title
            .description.more
              = review.summary.gsub("\n", "<br/>").html_safe
            .more-btn MORE
            .less-btn LESS
        .panel-footer
          .category= book.category

app/views/reviews/new.html.haml
%h1 New review

= render 'form'

.field
  %h2.pad-header
    Cancel and head
    = link_to 'Back', books_path
    ?

app/views/reviews/show.html.haml
%p#notice= notice

%p
  %b Book:
  = @review.book_id
%p
  %b User:
  = @review.user_id
%p
  %b Title:
  = @review.title
%p
  %b Summary:
  = @review.summary
%p
  %b Rating:
  = @review.rating
%p
  %b Recommended:
  = @review.recommended

= link_to 'Edit', edit_review_path(@review)
\|
= link_to 'Back', reviews_path

app/views/shared/_flash.html.haml
:javascript
  $(document).ready(function() {
    setTimeout(function() {
      $(".alert").slideUp();
    }, 5000);
  });

- flash.each do |key, value|
  %div{class: flash_class(key)}
    = value

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-default.navbar-fixed-top.navbar-inverse{role: "navigation"}
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: "/welcome", class: (params[:controller] == 'static' && params[:action] == 'welcome' ? 'active' : '')} Read. Share. Win.
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
      %ul.nav.navbar-nav.navbar-right
        %li
          %a{href: "/reviews"} Book Reviews
        %li
          %a{href: "/reading-list"} Reading List
        %li{ class: (params[:controller] == 'static' && params[:action] == 'timeline' ? 'active' : '') }
          %a{ href: "/timeline" } Dev Timeline
        - if user_signed_in?
          %li
            = link_to "Logout", destroy_user_session_path, :method => :delete
        - else
          %li
            = link_to "Sign In", new_user_session_path
    / /.navbar-collapse
  / /.container-fluid